export { MasterApp } from './MasterApp';
export {
  MASTER_MENU,
  MASTER_MENU_GROUPS,
  MASTER_DAILY_MENU,
  MASTER_SETTINGS_MENU,
  MASTER_MONITORING_MENU,
  MASTER_HIDDEN_MENU,
  OPERATIONAL_SCOPE,
} from './menu';
