export { DetailField } from './DetailField';
export { CommercialSummaryCard } from './CommercialSummaryCard';
export { CommercialPipeline } from './CommercialPipeline';
export { TechnicalProvisionPanel } from './TechnicalProvisionPanel';
export { LicensePanel } from './LicensePanel';
export { SubscriptionPanel } from './SubscriptionPanel';
export { CRMPanel } from './CRMPanel';
export { AutomationPipeline } from './AutomationPipeline';
export { UnifiedTimeline } from './UnifiedTimeline';
export { CustomerHealthPanel } from './CustomerHealthPanel';
export { QuickActionsPanel } from './QuickActionsPanel';
export { TechnicalLogsPanel } from './TechnicalLogsPanel';
export { buildUnifiedTimeline } from './buildUnifiedTimeline';
export { useMasterCompanyDetail } from './useMasterCompanyDetail';
export { formatDisplayDate, formatMoneyBrl } from './displayFormat';
